export const emptyResponse = {
  ok: false,
  redirected: false,
  type: 'error',
  status: 0,
  statusText: 'TimeoutError',
  url: '',
  clone: () => new Response(),
  arrayBuffer: () => Promise.resolve(new ArrayBuffer(0)),
  headers: new Headers(),
  formData: () => Promise.resolve(new FormData()),
  blob: () => Promise.resolve(new Blob()),
  json: () => Promise.resolve(),
  text: () => Promise.resolve(''),
  body: null,
  bodyUsed: false,
} as const;
