name: Release, deploy and update task

on:
  push:
    tags:
      - v*.*.*

jobs:
  kanboard:
    uses: moogur/all-workflows/.github/workflows/kanboard.yml@master
    secrets: inherit
    with:
      kanboard_columns: '51,38,39,40,41,42,43'
      project_type: 'multi_branch'
      event_type: 'deploy'

  release:
    needs: kanboard
    uses: moogur/all-workflows/.github/workflows/release_frontend.yml@master
    secrets: inherit
